# Generated by Django 5.2.4 on 2025-07-07 02:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consola',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('fabricante', models.CharField(max_length=100)),
                ('año_lanzamiento', models.IntegerField()),
            ],
        ),
        migrations.RenameField(
            model_name='reseña',
            old_name='comentario',
            new_name='contenido',
        ),
        migrations.RemoveField(
            model_name='reseña',
            name='fecha',
        ),
        migrations.RemoveField(
            model_name='reseña',
            name='puntuacion',
        ),
        migrations.RemoveField(
            model_name='videojuego',
            name='descripcion',
        ),
        migrations.RemoveField(
            model_name='videojuego',
            name='fecha_lanzamiento',
        ),
        migrations.RemoveField(
            model_name='videojuego',
            name='genero',
        ),
        migrations.AlterField(
            model_name='reseña',
            name='videojuego',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppCoder.videojuego'),
        ),
        migrations.AlterField(
            model_name='videojuego',
            name='titulo',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='videojuego',
            name='plataforma',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppCoder.consola'),
        ),
        migrations.CreateModel(
            name='Truco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField()),
                ('videojuego', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppCoder.videojuego')),
            ],
        ),
        migrations.DeleteModel(
            name='Plataforma',
        ),
    ]
