# Generated by Django 5.2.4 on 2025-07-09 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0002_consola_rename_comentario_reseña_contenido_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reseña',
            name='videojuego',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='truco',
            name='videojuego',
            field=models.CharField(max_length=100),
        ),
    ]
