# Generated by Django 5.2.4 on 2025-07-09 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0003_alter_reseña_videojuego_alter_truco_videojuego'),
    ]

    operations = [
        migrations.RenameField(
            model_name='consola',
            old_name='fabricante',
            new_name='empresa',
        ),
    ]
